DROP TABLE buildings;
DROP TABLE rooms;
DROP TABLE staffs;
DROP TABLE departments;
DROP TABLE students;
DROP TABLE student_accounts;
DROP TABLE student_invoices;
DROP TABLE student_payments;
DROP TABLE personal_information;