// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repositories

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Building struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Code          string             `json:"code"`
	Description   string             `json:"description"`
	NumberOfRooms int32              `json:"number_of_rooms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	IsActive      bool               `json:"is_active"`
}

type Room struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	BuildingID  int32              `json:"building_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	IsActive    bool               `json:"is_active"`
}
