// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: personalinfo-queries.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPersonalInfo = `-- name: InsertPersonalInfo :exec
INSERT INTO personal_information (
    nationality,
    city,
    address,
    dob,
    place_of_birth,
    father_name,
    mother_name,
    guardian_phone_number,
    passport_number,
    passport_issue_date,
    passport_expiry_date,
    passport_issuing_authority,
    student_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
`

type InsertPersonalInfoParams struct {
	Nationality              string      `json:"nationality"`
	City                     string      `json:"city"`
	Address                  string      `json:"address"`
	Dob                      pgtype.Date `json:"dob"`
	PlaceOfBirth             string      `json:"place_of_birth"`
	FatherName               string      `json:"father_name"`
	MotherName               string      `json:"mother_name"`
	GuardianPhoneNumber      string      `json:"guardian_phone_number"`
	PassportNumber           string      `json:"passport_number"`
	PassportIssueDate        pgtype.Date `json:"passport_issue_date"`
	PassportExpiryDate       pgtype.Date `json:"passport_expiry_date"`
	PassportIssuingAuthority string      `json:"passport_issuing_authority"`
	StudentID                pgtype.Int4 `json:"student_id"`
}

func (q *Queries) InsertPersonalInfo(ctx context.Context, arg InsertPersonalInfoParams) error {
	_, err := q.db.Exec(ctx, insertPersonalInfo,
		arg.Nationality,
		arg.City,
		arg.Address,
		arg.Dob,
		arg.PlaceOfBirth,
		arg.FatherName,
		arg.MotherName,
		arg.GuardianPhoneNumber,
		arg.PassportNumber,
		arg.PassportIssueDate,
		arg.PassportExpiryDate,
		arg.PassportIssuingAuthority,
		arg.StudentID,
	)
	return err
}

const updatePersonalInfo = `-- name: UpdatePersonalInfo :exec
UPDATE personal_information
SET 
    nationality = COALESCE($2, nationality),
    city = COALESCE($3, city),
    address = COALESCE($4, address),
    dob = COALESCE($5, dob),
    place_of_birth = COALESCE($6, place_of_birth),
    local_address = COALESCE($7, local_address),
    father_name = COALESCE($7, father_name),
    mother_name = COALESCE($8, mother_name),
    guardian_phone_number = COALESCE($9, guardian_phone_number),
    local_phone_number = COALESCE($10, local_phone_number),
    passport_number = COALESCE($11, passport_number),
    passport_issue_date = COALESCE($12, passport_issue_date),
    passport_expiry_date = COALESCE($13, passport_expiry_date),
    passport_issuing_authority = COALESCE($14, passport_issuing_authority),
    id_card_number = COALESCE($15, id_card_number),
    student_id = COALESCE($16, student_id),
    staff_id = COALESCE($17, staff_id),
    updated_at = CURRENT_TIMESTAMP
WHERE pid = $1
`

type UpdatePersonalInfoParams struct {
	Pid                      int32       `json:"pid"`
	Nationality              string      `json:"nationality"`
	City                     string      `json:"city"`
	Address                  string      `json:"address"`
	Dob                      pgtype.Date `json:"dob"`
	PlaceOfBirth             string      `json:"place_of_birth"`
	LocalAddress             pgtype.Text `json:"local_address"`
	MotherName               string      `json:"mother_name"`
	GuardianPhoneNumber      string      `json:"guardian_phone_number"`
	LocalPhoneNumber         pgtype.Text `json:"local_phone_number"`
	PassportNumber           string      `json:"passport_number"`
	PassportIssueDate        pgtype.Date `json:"passport_issue_date"`
	PassportExpiryDate       pgtype.Date `json:"passport_expiry_date"`
	PassportIssuingAuthority string      `json:"passport_issuing_authority"`
	IDCardNumber             pgtype.Text `json:"id_card_number"`
	StudentID                pgtype.Int4 `json:"student_id"`
	StaffID                  pgtype.Int4 `json:"staff_id"`
}

func (q *Queries) UpdatePersonalInfo(ctx context.Context, arg UpdatePersonalInfoParams) error {
	_, err := q.db.Exec(ctx, updatePersonalInfo,
		arg.Pid,
		arg.Nationality,
		arg.City,
		arg.Address,
		arg.Dob,
		arg.PlaceOfBirth,
		arg.LocalAddress,
		arg.MotherName,
		arg.GuardianPhoneNumber,
		arg.LocalPhoneNumber,
		arg.PassportNumber,
		arg.PassportIssueDate,
		arg.PassportExpiryDate,
		arg.PassportIssuingAuthority,
		arg.IDCardNumber,
		arg.StudentID,
		arg.StaffID,
	)
	return err
}
