// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repositories

import (
	"context"
)

type Querier interface {
	GetDepartmentById(ctx context.Context, departmentID int32) (Department, error)
	GetLastInsertedStudentId(ctx context.Context) (int32, error)
	InsertPersonalInfo(ctx context.Context, arg InsertPersonalInfoParams) error
	InsertStudent(ctx context.Context, arg InsertStudentParams) (int32, error)
	SelectAllBuildings(ctx context.Context) ([]Building, error)
	SelectAllRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
