// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package repositories

import (
	"context"
)

type Querier interface {
	SelectAllBuildings(ctx context.Context) ([]Building, error)
	SelectAllRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
